version: '2.4'

services:

  gen-req:
    build:
      context: ..
      dockerfile: docker/req.dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
    command: sh -c 'pip-compile requirements.in > requirements.txt'
    volumes:
      - $PWD/..:/req

  tool:
    image: brsynth/${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
    volumes:
      - cache:/home/cache
      - input_cache:/home/input_cache
    networks:
      - db

volumes:
  cache:
    external:
      name: ${RPCACHE}_cache
  input_cache:
    external:
      name: ${RPCACHE}_input_cache

networks:
  db:
    external:
      name: ${RPCACHE}_db
