version: '2.4'

services:

  rpreader:
    image: brsynth/${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
#    container_name: rpReader
    restart: always
    volumes:
      - cache:/home/cache
      - input_cache:/home/input_cache
    networks:
      - db

volumes:
  cache:
    external:
      name: ${RPCACHE}_cache
  input_cache:
    external:
      name: ${RPCACHE}_input_cache

networks:
  db:
    external:
      name: rpcache_db
