version: '2.4'

services:

  gen-req:
    image: python:3
    command: sh -c "
        /usr/local/bin/python -m pip install --upgrade pip
     && /usr/local/bin/python -m pip install pip-compile-multi
     && cd /req
     && pip-compile requirements.in > requirements.txt"
    volumes:
      - $PWD/..:/req

  rpcompletion:
    image: brsynth/${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
#    container_name: rpReader
    restart: always
    volumes:
      - cache:/home/cache
      - input_cache:/home/input_cache
    networks:
      - db

volumes:
  cache:
    external:
      name: ${RPCACHE}_cache
  input_cache:
    external:
      name: ${RPCACHE}_input_cache

networks:
  db:
    external:
      name: ${RPCACHE}_db
